ci:
  skip: [mypy]
  autoupdate_schedule: quarterly

repos:
# Syntax validation and some basic sanity checks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-merge-conflict
  - id: check-ast
    fail_fast: True
  - id: check-json
  - id: check-added-large-files
    args: ['--maxkb=200']
  - id: check-yaml

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.8
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix, --show-fixes]
    - id: ruff-format

# # Linting
# - repo: https://github.com/PyCQA/flake8
#   rev: 7.1.1
#   hooks:
#   - id: flake8
#     additional_dependencies: ['flake8-comprehensions==3.8.0']

# Type checking
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.13.0
  hooks:
  - id: mypy
    files: 'src/.*\.py$'
    additional_dependencies: ['types-setuptools==57.0.2']
