repos:

# Automatically sort imports
- repo: https://github.com/PyCQA/isort
  rev: 5.9.3
  hooks:
  - id: isort

# Automatic source code formatting
- repo: https://github.com/psf/black
  rev: 21.6b0
  hooks:
  - id: black
    args: [--safe, --quiet]

# Linting
- repo: https://github.com/PyCQA/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    additional_dependencies: ['flake8-comprehensions==3.5.0']

# Syntax validation and some basic sanity checks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-merge-conflict
  - id: check-ast
  - id: check-json
  - id: check-added-large-files
    args: ['--maxkb=200']
  - id: check-yaml
