trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'

stages:
- stage: build
  displayName: Build
  dependsOn:
  jobs:
  - job: build
    displayName: build package
    pool:
      vmImage: ubuntu-20.04
    steps:
      - task: UsePythonVersion@0
        displayName: Set up python
        inputs:
          versionSpec: 3.9

      - bash: |
          pip install -U pip
          pip install collective.checkdocs wheel
        displayName: Install dependencies

      - bash: |
          set -ex
          python setup.py sdist bdist_wheel
          mkdir -p dist/pypi
          shopt -s extglob
          mv -v dist/!(pypi) dist/pypi
          git archive HEAD | gzip > dist/repo-source.tar.gz
          ls -laR dist
        displayName: Build python package

      - task: PublishBuildArtifacts@1
        displayName: Store artifact
        inputs:
          pathToPublish: dist/
          artifactName: package

      - bash: python setup.py checkdocs
        displayName: Check package description

- stage: tests
  displayName: Run unit tests
  dependsOn:
  - build
  jobs:
  - job: linux
    pool:
      vmImage: ubuntu-20.04
    strategy:
      matrix:
        python36:
          PYTHON_VERSION: 3.6
        python39:
          PYTHON_VERSION: 3.9
    steps:
    - template: ci.yml
