steps:
- checkout: none

- bash: |
    set -eux
    mkdir rabbitmq-docker && cd rabbitmq-docker

    cat <<EOF >rabbitmq.conf
    # allowing remote connections for default user is highly discouraged
    # as it dramatically decreases the security of the system. Delete the user
    # instead and create a new one with generated secure credentials.
    loopback_users = none
    EOF

    cat <<EOF >Dockerfile
    FROM rabbitmq:3.9-management
    COPY rabbitmq.conf /etc/rabbitmq/rabbitmq.conf
    EOF

    docker build -t azure-rabbitmq .
    docker run --detach --name rabbitmq -p 127.0.0.1:5672:5672 -p 127.0.0.1:15672:15672 azure-rabbitmq
    docker container list -a
  displayName: Start RabbitMQ container
  workingDirectory: $(Pipeline.Workspace)

- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(PYTHON_VERSION)'
  displayName: 'Use Python $(PYTHON_VERSION)'

- task: DownloadBuildArtifacts@0
  displayName: Get pre-built package
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'package'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: ExtractFiles@1
  displayName: Checkout sources
  inputs:
    archiveFilePatterns: "$(System.ArtifactsDirectory)/package/repo-source.tar.gz"
    destinationFolder: "$(Pipeline.Workspace)/src"

- script: |
    set -eux
    pip install --disable-pip-version-check -r "$(Pipeline.Workspace)/src/requirements_dev.txt"
    pip install --no-deps --disable-pip-version-check -e "$(Pipeline.Workspace)/src"
  displayName: Install package

- script: |
    wget -t 10 -w 1 http://127.0.0.1:15672 -O -
  displayName: Check RabbitMQ is alive

- script: |
    PYTHONDEVMODE=1 pytest -v -ra --cov=workflows --cov-report=xml --cov-branch
  displayName: Run tests
  workingDirectory: $(Pipeline.Workspace)/src

- bash: bash <(curl -s https://codecov.io/bash) -t $(CODECOV_TOKEN) -n "Python $(PYTHON_VERSION) $(Agent.OS)"
  displayName: Publish coverage stats
  continueOnError: True
  workingDirectory: $(Pipeline.Workspace)/src
  timeoutInMinutes: 2

- script: |
    docker logs rabbitmq
    docker stop rabbitmq
  displayName: Show RabbitMQ logs
  condition: succeededOrFailed()
